### PR TITLE
Catch rework

### PR DESCRIPTION
**Pull request by JensWehner**
should reduce compile times according to https://github.com/catchorg/Catch2/blob/master/docs/slow-compiles.md#top

### CODE REVIEW

**Comment by yixuan** [comment]
Seems the source file of `tests-main` is missing?

**Comment by JensWehner** [comment]
good point

**Review by yixuan — APPROVED** [review]
I tested this method and it was a **GREAT** improvement. On my machine the total build time reduces to 2min from 5min. :+1:

**Comment by yixuan** [comment]
I think it is ready to merge. The only issue is that this PR does not pass Travis CI since the test takes too long. To fix it we need to add proper optimization flags (e.g. `-O2`) to the build script. I guess some CMake options need to be modified?

**Comment by JensWehner** [comment]
yes I took them out because I thought debug should be proper debug mode, but then the tests take 4-5h. github actions can handle it but not travis.

**Comment by JensWehner** [comment]
Either we make the tests smaller or we add optimisation flags.

**Comment by yixuan** [comment]
I see. Shall we merge this first and then fix it in the [6_jd_base_solver](https://github.com/NLESC-JCER/spectra/tree/6_jd_base_solver) branch later?

**Pull request merged**
